name: Build Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: sudo apt-get install pandoc
      - name: Convert Markdown to HTML
        run: |
          for file in $(find . -name "*.md"); do
              pandoc -s "$file" -o "${file%.md}.html"
          done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./
